name: fer_detection_app
description: "Application that detects human face expressions in real time using Google ML Kit and TensorFlow Lite"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^11.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  google_mlkit_face_detection: ^0.13.2
  image_picker: ^1.2.1
  camera: ^0.11.3
  tflite_flutter: ^0.12.1
  image: ^4.1.3
  riverpod: ^3.1.0
  progress_indicator_m3e: ^0.1.1
  google_fonts: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

